Repository Together-Java/TJ-Bot, pull requests merged in 2021-11, with the labels that each got.

#245 Added .DS_STORE to gitignore (mac users)
  .gitignore
Labels: enhancement

#246 Fix broken mockito bump (3.12.4 -> 4.0.0)
  application/build.gradle
Labels: dependencies

#243 Improves UX which replaces ID with applications name.
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
Labels: enhance command, priority: low

#256 Update gradle to 7.3
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, priority: major, dependencies

#259 Simplify merge conflicts when adding new commands
  application/src/main/java/org/togetherjava/tjbot/commands/Commands.java
Labels: enhancement, priority: low

#260 Added CLA
  CLA.md
Labels: enhancement

#262 Update CLA
  CLA.md
Labels: enhancement

#261 Changed VC-Activity message
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
Labels: enhance command

#271 Fixed bug with tag-raw not working with code snippets
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/test/java/org/togetherjava/tjbot/commands/utils/MessageUtilsTest.java
Labels: bug, priority: major
