Repository Together-Java/TJ-Bot, pull requests merged in 2021-09, with the labels that each got.

#7 Create README.md
  README.md
Labels: documentation

#9 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#11 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#15 Added code quality badge
  README.md
Labels: documentation

#14 Add comments to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#22 "GitHub Polls Bot Actions" Integration
  .github/workflows/github_polls_actions_bot.yml
Labels: enhancement

#28 Initial setup (!ping command)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/togetherjava/tjbot/Main.java
  src/main/java/org/togetherjava/tjbot/PingPongListener.java
  src/main/java/org/togetherjava/tjbot/package-info.java
  src/main/resources/log4j2.xml
  src/test/java/org/togetherjava/tjbot/MainTest.java
Labels: enhancement

#35 Fix spotless
  build.gradle
Labels: bug

#34 Bump gradle version & Add compatibility versions
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#39 Add a dependabot config
  .github/dependabot.yml
Labels: enhancement

#43 Align chopped down chains at "." character
  meta/formatting/google-style-eclipse.xml
  src/main/java/org/togetherjava/tjbot/Main.java
Labels: bug

#49 Basic command interface and examples
  src/main/java/org/togetherjava/tjbot/Main.java
  src/main/java/org/togetherjava/tjbot/commands/Command.java
  src/main/java/org/togetherjava/tjbot/commands/example/CommandExample.java
  src/main/java/org/togetherjava/tjbot/commands/example/SubCommandExample.java
Labels: enhancement

#46 Added SQLite and simple example commands
  .gitignore
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/DatabaseListener.java
Labels: enhancement

#54 Changed invite link in readme
  README.md
Labels: documentation

#74 Add workflows for docker build and publish
  .github/workflows/docker-build.yaml
  .github/workflows/docker-publish.yaml
  application/build.gradle
Labels: enhancement

#78 Consolidate github workflows
  .github/workflows/basic-checks.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/spotless.yml
  .github/workflows/tests.yaml
Labels: enhancement

#80 Add Tech Stack Diagram
  meta/TJ-Bot Tech Stack Diagram.drawio.xml
Labels: documentation

#81 Polished documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#84 Fix the README.md #download section
  README.md
Labels: documentation, priority: normal

#85 Create the build dir for flyway if it doesn't exist
  application/build.gradle
Labels: bug

#86 Various improvements to the DB code
  .gitignore
  application/src/main/java/org/togetherjava/tjbot/DatabaseListener.java
  application/src/main/java/org/togetherjava/tjbot/db/Database.java
  application/src/main/java/org/togetherjava/tjbot/db/DatabaseException.java
Labels: enhancement

#90 Run workflows with pull requests's version
  .github/workflows/basic-checks.yml
  .github/workflows/codeql.yml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-publish.yaml
Labels: enhancement

#96 Run sonar on pull_request_target to ensure it sees secrets
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
Labels: bug

#98 Add some basic access checks to the example database command
  application/src/main/java/org/togetherjava/tjbot/DatabaseListener.java
Labels: enhancement

#99 Change codeql and sonarqube workflow name
  .github/workflows/code-analysis.yml
Labels: enhancement

#110 Create Github releases with a runnable jar on tag push
  .github/workflows/releases.yaml
  application/build.gradle
Labels: enhancement

#41 Add formatter
  formatter/build.gradle
  formatter/src/main/java/org/togetherjava/formatter/CodeSectionFormatter.java
  formatter/src/main/java/org/togetherjava/formatter/Formatter.java
  formatter/src/main/java/org/togetherjava/formatter/tokenizer/Lexer.java
  formatter/src/main/java/org/togetherjava/formatter/tokenizer/Token.java
  formatter/src/main/java/org/togetherjava/formatter/tokenizer/TokenType.java
  formatter/src/main/java/org/togetherjava/formatter/tokenizer/TokenizationException.java
  formatter/src/main/java/org/togetherjava/formatter/util/LookaheadArrayDeque.java
  formatter/src/main/java/org/togetherjava/formatter/util/LookaheadQueue.java
  formatter/src/main/java/org/togetherjava/formatter/util/SkippableLookaheadArrayDeque.java
  formatter/src/main/java/org/togetherjava/formatter/util/SkippableLookaheadQueue.java
  formatter/src/test/java/org/togetherjava/formatter/FormatterTest.java
  formatter/src/test/java/org/togetherjava/formatter/tokenizer/LexerTest.java
  meta/formatting/google-style-eclipse.xml
  settings.gradle
Labels: enhancement

#116 Modularize database
  application/build.gradle
  database/build.gradle
  database/src/main/java/org/togetherjava/tjbot/db/Database.java
  database/src/main/java/org/togetherjava/tjbot/db/DatabaseException.java
  database/src/main/java/org/togetherjava/tjbot/db/package-info.java
  database/src/main/java/org/togetherjava/tjbot/db/util/CheckedConsumer.java
  database/src/main/java/org/togetherjava/tjbot/db/util/CheckedFunction.java
  database/src/main/java/org/togetherjava/tjbot/db/util/package-info.java
  settings.gradle
Labels: enhancement

#118 Move database migration scripts to database module
  database/src/main/resources/db/V1__Database_Listener.sql
Labels: bug

#122 Remove db package-info from application module
  application/src/main/java/org/togetherjava/tjbot/db/package-info.java
Labels: bug

#125 Fix some command things
  application/src/main/java/org/togetherjava/tjbot/commands/CommandHandler.java
  application/src/main/java/org/togetherjava/tjbot/commands/example/CommandExample.java
Labels: enhancement

#133 Rollback of the discord invite link
  README.md
Labels: documentation

#134 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement, priority: major

#142 Added config file support
  .gitignore
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
Labels: enhancement

#143 Add shutdown hook
  application/src/main/java/org/togetherjava/tjbot/Application.java
Labels: enhancement
