Repository Together-Java/TJ-Bot, pull requests merged in 2022-01, with the labels that each got.

#343 VC Activity command crash fix #300
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
Labels: bug, priority: normal

#332 Add optional reply-to support to tag command
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagCommand.java
Labels: enhance command, priority: normal

#348 Add config template
  application/config.json.template
Labels: documentation, enhancement, priority: major

#342 Removes title for all AuditLog
  application/src/main/java/org/togetherjava/tjbot/routines/ModAuditLogRoutine.java
Labels: enhance command, priority: normal
