Repository Together-Java/TJ-Bot, pull requests merged in 2022-11, with the labels that each got.

#668 Delete scam help threads
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/UserBannedDeleteRecentThreadsListener.java
Labels: enhancement, priority: normal

#661 Add tests for TopHelperMessageListener
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersMessageListener.java
  application/src/test/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListenerTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/tophelper/TopHelperMessageListenerTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/JdaTester.java
Labels: enhancement, priority: low

#622 Add code format command
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageReceiver.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageReceiverAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeMessageHandler.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/FormatCodeCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/package-info.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/CodeFence.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/test/java/org/togetherjava/tjbot/commands/utils/MessageUtilsTest.java
  formatter/build.gradle
  formatter/src/main/java/org/togetherjava/tjbot/formatter/CodeSectionFormatter.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/Formatter.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/formatting/CodeSectionFormatter.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/formatting/FormatterRules.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/formatting/TokenQueue.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/formatting/package-info.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/Lexer.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/Matching.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/Token.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/TokenType.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/TokenizationException.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/util/LookaheadArrayDeque.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/util/LookaheadQueue.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/util/SkippableLookaheadArrayDeque.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/util/SkippableLookaheadQueue.java
  formatter/src/test/java/org/togetherjava/tjbot/formatter/FormatterTest.java
  formatter/src/test/java/org/togetherjava/tjbot/formatter/formatting/FormatterRulesTest.java
  formatter/src/test/java/org/togetherjava/tjbot/formatter/formatting/TokenQueueTest.java
  formatter/src/test/java/org/togetherjava/tjbot/formatter/tokenizer/LexerTest.java
  formatter/src/test/java/org/togetherjava/tjbot/formatter/tokenizer/MatchingTest.java
Labels: new command, priority: major

#682 Code-Actions improvements
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeMessageAutoDetection.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeMessageHandler.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeMessageManualDetection.java
Labels: new command, enhance command, priority: major

#653 Report Command
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ReportCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/modmail/ModMailCommand.java
Labels: new command, priority: normal

#684 Some tweaks to the helper prune system
  application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java
Labels: enhancement, priority: low

#616 Link/Image previews for tags
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreview.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreviews.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/StringDistances.java
Labels: enhance command, priority: major

#698 Added widgetbot to the website
  website/src/main/resources/public/index.html
Labels: enhancement, priority: normal

#693 Files without extenions are blacklisted now
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/attachment/BlacklistedAttachmentListener.java
Labels: bug, priority: low

#696 Fixed a small OOB bug with extracting code
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
Labels: bug, priority: low

#699 Ping moderators when /modmail and /report commands are used.
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ReportCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/modmail/ModMailCommand.java
Labels: enhance command, priority: normal

#634 Bookmark Command
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/BookmarksCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/BookmarksListRemoveHandler.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/BookmarksSystem.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/LeftoverBookmarksCleanupRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/LeftoverBookmarksListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/package-info.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/main/resources/db/V12__Add_Bookmarks_System.sql
Labels: enhancement, new command, priority: normal

#703 Fixed bug with linkpreview OG twitter broken
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreviews.java
Labels: bug, priority: critical

#704 Release v3.11.1
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreviews.java
Labels: release
