Repository Together-Java/TJ-Bot, pull requests merged in 2022-03, with the labels that each got.

#410 Colorblind support for help system emojis
  application/src/main/java/org/togetherjava/tjbot/commands/free/ChannelStatusType.java
Labels: good first issue, enhance command, priority: normal

#412 Bugfix - Handling blocked users gracefully when reacting to their messages
  application/src/main/java/org/togetherjava/tjbot/commands/basic/SuggestionsUpDownVoter.java
Labels: bug, enhancement

#417 Removed code duplication from role based moderation actions.
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/RevocableRoleBasedAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryMuteAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryQuarantineAction.java
Labels: enhancement, priority: major
