Repository Together-Java/TJ-Bot, pull requests merged in 2022-08, with the labels that each got.

#472 Audit rework
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java
Labels: bug, enhance command, priority: normal

#473 Updated map of VC activities
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
Labels: enhance command, priority: low

#477 Update stale action v3 -> v4
  .github/workflows/stale.yml
Labels: priority: normal, dependencies

#476 Made #active_questions post more robust against hicups
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
Labels: enhancement, priority: normal

#496 Increase dependabot support
  .github/dependabot.yml
Labels: enhancement, priority: low

#514 fixed unknown class referenced
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentId.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdGenerator.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdParser.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdStore.java
Labels: enhancement, priority: low

#494 Adding uncaught exception handling
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdStore.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
Labels: enhancement, priority: major

#492 Added help thread activity detection
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/BotMessageCleanup.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
Labels: enhancement, priority: normal

#491 Gist auto filesharing in help threads
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/GistFile.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/GistFiles.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/GistRequest.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/GistResponse.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/package-info.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
Labels: enhancement, priority: normal

#495 Auto-prune of full helper roles
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/main/java/org/togetherjava/tjbot/moderation/ModAuditLogWriter.java
  application/src/main/resources/log4j2.xml
Labels: enhancement, priority: major

#524 Implement thread close reminder for ask threads
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: enhancement, priority: normal

#529 Replaces enum-utility-pattern classes with regular noninstantiable classes
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/BootstrapLauncher.java
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/wolframalpha/WolframAlphaImages.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/Hashing.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/StringDistances.java
Labels: enhancement, priority: normal

#530 Fixed attachment error + close input stream correctly
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/FileSharingMessageListener.java
Labels: bug, priority: major

#528 Adding org website
  settings.gradle
  website/build.gradle
  website/src/main/java/org/togetherjava/tjbot/website/Application.java
  website/src/main/resources/application.properties
  website/src/main/resources/public/index.html
Labels: enhancement, priority: normal

#517 remove unnecessary checks
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpCategoryCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpTitleCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/CloseCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/NoteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnbanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WarnCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagManageCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java
  application/src/test/java/org/togetherjava/tjbot/commands/tags/TagManageCommandTest.java
Labels: enhancement, priority: normal

#534 Make readme more inviting to contributors
  README.md
Labels: documentation, priority: normal

#497 Auto-close help thread if OP leaves server
  PP.md
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadMetadataPurger.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/OnGuildLeaveCloseThreadListener.java
  application/src/main/resources/db/V11__Add_Help_Thread_Metadata.sql
Labels: enhancement, priority: normal

#518 Only allow media posts in media channels
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListener.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/test/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListenerTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/JdaTester.java
Labels: enhancement, priority: normal

#527 Fix bug with /audit unable to retrieve users
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java
Labels: bug, priority: major

#537 Disallow 'help' in title of help threads
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: enhance command, priority: normal

#540 Adding help thread auto archiver
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
Labels: enhancement, priority: major

#544 Allow linked media posts
  application/src/main/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListener.java
  application/src/test/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListenerTest.java
Labels: bug, priority: normal
