Repository Together-Java/TJ-Bot, pull requests merged in 2022-10, with the labels that each got.

#597 Bugfix command completion not working
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
Labels: bug, priority: normal

#574 Grouped help thread commands
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpCategoryCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpTitleCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/CloseCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
Labels: enhance command, priority: normal

#601 Fixed components not working
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/test/java/org/togetherjava/tjbot/commands/SlashCommandAdapterTest.java
Labels: bug, priority: major

#587 Migrate to JDA alpha 20
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/RoleSelectCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/SuggestionsUpDownVoter.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdGenerator.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdParser.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/BotMessageCleanup.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/OnGuildLeaveCloseThreadListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/TeXCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/wolframalpha/WolframAlphaCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/wolframalpha/WolframAlphaHandler.java
  application/src/main/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/attachment/BlacklistedAttachmentListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryMuteAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryQuarantineAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/reminder/RemindRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagManageCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagSystem.java
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/moderation/ModAuditLogWriter.java
  application/src/main/java/org/togetherjava/tjbot/routines/ModAuditLogRoutine.java
  application/src/test/java/org/togetherjava/tjbot/commands/mathcommands/TeXCommandTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListenerTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/reminder/RawReminderTestHelper.java
  application/src/test/java/org/togetherjava/tjbot/commands/reminder/RemindRoutineTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/tags/TagManageCommandTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/tags/TagsCommandTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/ButtonClickEventBuilder.java
  application/src/test/java/org/togetherjava/tjbot/jda/JdaTester.java
Labels: priority: normal, dependencies

#592 Ensure config is present and not null
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/config/HelpSystemConfig.java
  application/src/main/java/org/togetherjava/tjbot/config/ScamBlockerConfig.java
  application/src/main/java/org/togetherjava/tjbot/config/SuggestionsConfig.java
Labels: bug, priority: low

#579 Forward logs to Discord
  application/build.gradle
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdStore.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/NoteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/RejoinModerationRoleListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnbanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WarnCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/RevocableRoleBasedAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryBanAction.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryModerationRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagManageCommand.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/logging/LogMarkers.java
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogAppender.java
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogForwarder.java
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogging.java
  application/src/main/java/org/togetherjava/tjbot/logging/discord/package-info.java
Labels: enhancement, priority: normal

#613 Added missing Javadoc to DiscordClientAction
  application/src/main/java/org/togetherjava/tjbot/commands/utils/DiscordClientAction.java
Labels: documentation, priority: low

#615 Format injection in help thread titles
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
Labels: bug, priority: normal

#612 Added missing package-infos
  formatter/build.gradle
  formatter/src/main/java/org/togetherjava/tjbot/formatter/package-info.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/tokenizer/package-info.java
  formatter/src/main/java/org/togetherjava/tjbot/formatter/util/package-info.java
Labels: enhancement, priority: normal

#610 Adding stacktraces to discord logs
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogForwarder.java
Labels: enhancement, priority: normal

#617 Auto-pin first message in help threads
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
Labels: enhancement, priority: normal

#611 Replaced overview message to embed
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
Labels: bug, priority: normal

#565 Use slash-command mentions (#559)
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
Labels: enhancement, priority: normal

#614 TopHelpersCommand message is too long
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogForwarder.java
  application/src/test/java/org/togetherjava/tjbot/commands/utils/MessageUtilsTest.java
Labels: bug, priority: normal

#624 Fix javadoc link in ModerationUtils
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
Labels: documentation, priority: low

#623 Fixed issue with closing already closed threads on guild leave
  application/src/main/java/org/togetherjava/tjbot/commands/help/OnGuildLeaveCloseThreadListener.java
Labels: bug, priority: low

#588 Added ComponentIdInteractor delegate
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractionType.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractor.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractorPrefix.java
  application/src/main/java/org/togetherjava/tjbot/commands/componentids/ComponentIdInteractor.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/CommandProvider.java
  application/src/test/java/org/togetherjava/tjbot/commands/SlashCommandAdapterTest.java
Labels: enhancement, priority: normal

#625 Fixed some minor syntax issue after lots of rebases
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogForwarder.java
Labels: bug, priority: critical

#598 added auto-complete for tag command
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/StringDistances.java
  application/src/test/java/org/togetherjava/tjbot/commands/utils/StringDistancesTest.java
Labels: enhance command, priority: normal

#629 Disabled JOOQ startup spam
  database/src/main/java/org/togetherjava/tjbot/db/Database.java
Labels: enhancement, priority: low

#628 Added POC for /google command
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/search/GoogleCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/search/GoogleItCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/search/GoogleResponseComposer.java
  application/src/main/java/org/togetherjava/tjbot/commands/search/GoogleSearchStrategy.java
  application/src/main/java/org/togetherjava/tjbot/commands/search/SearchStrategy.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
Labels: new command, priority: normal

#640 Fix JOOQ version mismatch
  buildSrc/src/main/groovy/database-settings.gradle
Labels: bug, priority: normal, dependencies

#626 Implemented modal support
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractor.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/RoleSelectCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
Labels: enhancement, priority: normal

#493 Adding the /modmail command
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WarnCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/attachment/BlacklistedAttachmentListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/attachment/package-info.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/modmail/ModMailCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/modmail/package-info.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/MessageUtils.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
Labels: new command, priority: normal

#649 Fix Top-Helper message length exploit
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersMessageListener.java
Labels: bug, priority: low

#657 Fixed issue with jooq version
  application/build.gradle
  build.gradle
  buildSrc/src/main/groovy/database-settings.gradle
  database/build.gradle
Labels: priority: normal, dependencies

#659 Fix and speed up top helper anticheat
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersMessageListener.java
Labels: bug, priority: critical

#658 Added suspicious keywords to scam blocker
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/scam/ScamDetector.java
  application/src/main/java/org/togetherjava/tjbot/config/ScamBlockerConfig.java
  application/src/test/java/org/togetherjava/tjbot/commands/moderation/scam/ScamDetectorTest.java
Labels: enhancement, priority: normal
