Repository Together-Java/TJ-Bot, pull requests merged in 2022-07, with the labels that each got.

#464 Bugfix with temp actions being revoked too early
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ActionRecord.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/RejoinModerationRoleListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryModerationRoutine.java
Labels: bug, priority: normal

#466 Bugfix with /change_help_title allowing too long titles
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpTitleCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: bug, priority: normal

#465 Bugfix when creating help threads, no bot-messages
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
Labels: bug, priority: normal

#467 Upgrade to Java 18
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/releases.yaml
  README.md
  application/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: priority: normal, dependencies

#469 Auto create threads for suggestions
  application/src/main/java/org/togetherjava/tjbot/commands/basic/SuggestionsUpDownVoter.java
Labels: enhancement, priority: normal
