Repository Together-Java/TJ-Bot, pull requests merged in 2022-12, with the labels that each got.

#706 Fixed bugs with link preview
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreviews.java
Labels: bug, priority: major

#708 Release v3.11.2
  application/src/main/java/org/togetherjava/tjbot/commands/utils/LinkPreviews.java
Labels: release

#709 Fix link for report's 'go to message' button
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/ReportCommand.java
Labels: bug, priority: major

#646 Auto post advice
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
Labels: enhancement, priority: normal

#705 Migrated help system to forums
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/BookmarksSystem.java
  application/src/main/java/org/togetherjava/tjbot/commands/code/CodeMessageAutoDetection.java
  application/src/main/java/org/togetherjava/tjbot/commands/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/BotMessageCleanup.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCreatedListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadOverviewUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/config/HelpSystemConfig.java
  application/src/test/java/org/togetherjava/tjbot/commands/tophelper/TopHelperMessageListenerTest.java
Labels: enhancement, priority: major

#724 Fixed bug with help thread creation actions being send too fast
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCreatedListener.java
Labels: bug, priority: major

#728 Removed share hint
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: enhancement, priority: normal

#727 Fixed package info for help package and removed NotNull annotations
  application/src/main/java/org/togetherjava/tjbot/commands/bookmarks/LeftoverBookmarksListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCreatedListener.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/package-info.java
Labels: bug, priority: normal

#731 Prefer uncommon categories first
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: enhancement, priority: normal
