Repository Together-Java/TJ-Bot, pull requests merged in 2022-09, with the labels that each got.

#553 Fixed typo in blacklist
  application/config.json.template
Labels: bug, priority: low

#556 fixes thread creation warns in media only channels
  application/src/main/java/org/togetherjava/tjbot/commands/mediaonly/MediaOnlyChannelListener.java
Labels: bug, priority: major

#554 Auto posting advice on uncategorized help threads
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ImplicitAskListener.java
Labels: enhancement, priority: normal

#577 Website SEO
  website/src/main/resources/public/assets/js/jquery-3.6.1.min.js
  website/src/main/resources/public/assets/js/jquery.scrollex.min.js
  website/src/main/resources/public/images/favicons/android-chrome-192x192.png
  website/src/main/resources/public/images/favicons/android-chrome-512x512.png
  website/src/main/resources/public/images/favicons/apple-touch-icon.png
  website/src/main/resources/public/images/favicons/favicon-16x16.png
  website/src/main/resources/public/images/favicons/favicon-32x32.png
  website/src/main/resources/public/images/favicons/favicon.ico
  website/src/main/resources/public/index.html
  website/src/main/resources/public/manifest.json
Labels: enhancement, priority: normal

#581 Rephrased auto-close message for UX
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadAutoArchiver.java
Labels: enhancement, priority: low

#583 Changing auto archiving from 24 to 12h
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadAutoArchiver.java
Labels: enhancement

#584 added comma for clarity
  TOS.md
Labels: documentation, enhancement, priority: low

#580 fixed bot positing advice on closed uncategorized help threads
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
Labels: bug, priority: normal

#558 Command rework, attempt number 2
  application/src/main/java/org/togetherjava/tjbot/Application.java
  application/src/main/java/org/togetherjava/tjbot/CommandReloading.java
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/CommandVisibility.java
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/MessageContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/SlashCommandAdapter.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserContextCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractor.java
  application/src/main/java/org/togetherjava/tjbot/commands/UserInteractorPrefix.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/PingCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/RoleSelectCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/AskCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpCategoryCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpTitleCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/CloseCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/TeXCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/mathcommands/wolframalpha/WolframAlphaCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/AuditCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/NoteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnbanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WarnCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WhoIsCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/reminder/RemindCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/BotCore.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/CommandProvider.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/LogLevelCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/ReloadCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/system/SlashCommandProvider.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagManageCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tags/TagsCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java
  application/src/test/java/org/togetherjava/tjbot/commands/SlashCommandAdapterTest.java
  application/src/test/java/org/togetherjava/tjbot/commands/system/ReloadCommandTest.java
Labels: documentation, enhancement, priority: major
