Repository Together-Java/TJ-Bot, pull requests merged in 2022-04, with the labels that each got.

#424 Optional month-selection for /top-helpers
  application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java
Labels: enhance command, priority: low

#431 Added missing Javadoc for public return value
  application/src/main/java/org/togetherjava/tjbot/moderation/ModAuditLogWriter.java
Labels: bug, documentation, priority: major

#434 Bugfix/helpsystem busy not working
  application/src/main/java/org/togetherjava/tjbot/commands/free/FreeCommand.java
Labels: bug, priority: critical
