Repository Together-Java/TJ-Bot, pull requests merged in 2022-02, with the labels that each got.

#370 Removed VC activities that didn't work
  application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
Labels: bug, good first issue, priority: low

#372 Temp revocation should use opposing type
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/temp/TemporaryModerationRoutine.java
Labels: bug, priority: normal

#374 Added tags to deactivate auto-stale
  .github/workflows/stale.yml
Labels: enhancement, priority: normal

#379 Added TOS and PP
  PP.md
  TOS.md
Labels: enhancement, priority: critical

#351 Reaction roles using a SelectionMenu
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/basic/RoleSelectCommand.java
Labels: new command, priority: normal

#383 Renamed Staff Assistants to Maintainers
  .github/CODEOWNERS
Labels: enhancement

#389 Removal of ALL subcommand on RoleSelectCommand
  application/src/main/java/org/togetherjava/tjbot/commands/basic/RoleSelectCommand.java
Labels: good first issue, enhance command, priority: normal

#395 Skipping audit logs against bot message deletions
  application/src/main/java/org/togetherjava/tjbot/routines/ModAuditLogRoutine.java
Labels: enhancement, priority: low

#391 Utility for in-app URL's
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/utils/DiscordClientAction.java
Labels: documentation, enhancement, priority: low
