Repository Together-Java/TJ-Bot, pull requests merged in 2023-01, with the labels that each got.

#744 Fix modmail NPE when sent from DMs
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/modmail/ModMailCommand.java
Labels: bug, priority: major

#745 Fixed config template formatting
  application/config.json.template
Labels: enhancement, priority: normal

#741 removed thread deletion on user ban feature
  application/src/main/java/org/togetherjava/tjbot/commands/Features.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/UserBannedDeleteRecentThreadsListener.java
Labels: enhancement, priority: low

#750 Added defer reply to mod commands
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/moderation/WarnCommand.java
Labels: bug, priority: normal

#739 Features/add command to reset activity for a help thread
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java
  application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadCommand.java
Labels: enhancement, new command, priority: major

#737 Added cancel feature to reminder command
  application/src/main/java/org/togetherjava/tjbot/commands/reminder/ReminderCommand.java
Labels: enhancement, new command, enhance command, priority: low
