Repository Together-Java/TJ-Bot, pull requests merged in 2023-09, with the labels that each got.

#853 use - in channel names
  application/config.json.template
Labels: enhancement, priority: low

#888 Fixed some ChatGPT issues
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptService.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: bug, priority: major

#889 Helper prune config
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/config/HelperPruneConfig.java
  application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java
Labels: enhancement, priority: major

#893 Pin the correct message in questions thread
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: enhancement, priority: normal

#903 Update Workflows
  .github/workflows/code-analysis.yml
Labels: priority: normal, dependencies
