Repository Together-Java/TJ-Bot, pull requests merged in 2023-03, with the labels that each got.

#779 Handling /reminder failure cases
  application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java
  application/src/main/resources/db/V13__Add_Reminder_Failure_attempts.sql
  application/src/test/java/org/togetherjava/tjbot/features/reminder/RemindRoutineTest.java
Labels: bug, priority: normal

#791 upgrade gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, priority: normal

#792 Java 18 -> Java 19
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/releases.yaml
  README.md
  application/build.gradle
  build.gradle
Labels: priority: normal, dependencies

#793 Style: changed delete icon for CodeMessageHandler
  application/src/main/java/org/togetherjava/tjbot/features/code/CodeMessageHandler.java
Labels: enhancement, priority: normal

#794 Upgrade java to 19 for website subproject
  website/build.gradle
Labels: bug, priority: critical

#796 used github api for creating gists
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/GistFile.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/GistFiles.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/GistRequest.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/GistResponse.java
Labels: enhancement, priority: low

#800 add modal support to /modmail command
  .gitignore
  application/src/main/java/org/togetherjava/tjbot/features/moderation/modmail/ModMailCommand.java
Labels: enhance command, priority: normal

#807 Logo Update
  website/src/main/resources/public/images/favicons/android-chrome-192x192.png
  website/src/main/resources/public/images/favicons/android-chrome-512x512.png
  website/src/main/resources/public/images/favicons/apple-touch-icon.png
  website/src/main/resources/public/images/favicons/favicon-16x16.png
  website/src/main/resources/public/images/favicons/favicon-32x32.png
  website/src/main/resources/public/images/favicons/favicon.ico
  website/src/main/resources/public/images/logo_frame.png
Labels: enhancement, priority: normal

#808 Update to SlashCommandEducator to exclude strings that end with ")" o…
  application/src/main/java/org/togetherjava/tjbot/features/basic/SlashCommandEducator.java
  application/src/test/java/org/togetherjava/tjbot/features/basic/SlashCommandEducatorTest.java
Labels: enhancement, priority: low

#810 ChatGPT Intialization
  application/build.gradle
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/chaptgpt/ChatGptCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/chaptgpt/ChatGptService.java
  application/src/main/java/org/togetherjava/tjbot/features/chaptgpt/package-info.java
  build.gradle
Labels: new command, priority: major

#811 Major bugfix with broken Bootstrap
  application/build.gradle
Labels: bug, priority: show-stopper
