Repository Together-Java/TJ-Bot, pull requests merged in 2023-10, with the labels that each got.

#902 Bump Java Version to 20
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/releases.yaml
  README.md
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/features/mathcommands/wolframalpha/WolframAlphaHandler.java
  application/src/main/java/org/togetherjava/tjbot/features/mathcommands/wolframalpha/WolframAlphaImages.java
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: priority: normal, dependencies

#909 Catch error when unable to send DM
  application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java
Labels: bug, priority: normal

#905 Transfer Feature reopen
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: enhancement, priority: normal

#916 Remove Stale-Bot
  .github/workflows/stale.yml
Labels: enhancement

#901 ChatGPT response Dismiss button
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: enhancement, priority: normal

#929 handle bot messages transfer action
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: bug, priority: normal

#932 refactor method for generating title of forum post
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: bug, priority: normal
