Repository Together-Java/TJ-Bot, pull requests merged in 2023-11, with the labels that each got.

#934 Issue #922 :Removing some hints in helps-thread
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/resources/codeSyntaxExample.png
Labels: enhancement, priority: normal

#943 bug-fix transfer feature
  application/src/main/java/org/togetherjava/tjbot/features/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/ReportCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/audit/AuditCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/audit/ModAuditLogRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
Labels: bug, priority: major

#951 Bug/ allows OP of embed from transfer to dismiss GPT's response
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: bug, priority: normal

#955 refactor onModalSubmit in TransferQuestionCommand to handle multiple users submission
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: bug, priority: normal

#957 improve suggestion for archived thread due to inactivity
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: enhancement, priority: normal

#960 used ephemeral response in question transfer
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: enhance command, priority: normal

#964 bug/archive flow moved inside retrieve member action
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
Labels: bug, priority: major
