Repository Together-Java/TJ-Bot, pull requests merged in 2023-02, with the labels that each got.

#647 Enhanced mod action dm message
  application/src/main/java/org/togetherjava/tjbot/features/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/WarnCommand.java
Labels: enhance command, priority: normal, valid

#759 Educate about /foo when ?!.foo
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/MessageReceiverAdapter.java
  application/src/main/java/org/togetherjava/tjbot/features/basic/SlashCommandEducator.java
  application/src/main/java/org/togetherjava/tjbot/features/code/CodeMessageAutoDetection.java
  application/src/main/java/org/togetherjava/tjbot/features/code/CodeMessageHandler.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/attachment/BlacklistedAttachmentListener.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/features/tophelper/TopHelpersMessageListener.java
  application/src/main/resources/slashCommandPopupAdvice.png
  application/src/test/java/org/togetherjava/tjbot/features/basic/SlashCommandEducatorTest.java
  application/src/test/java/org/togetherjava/tjbot/features/reminder/RemindRoutineTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/JdaTester.java
Labels: enhancement, priority: normal

#763 Top helpers not askers
  application/src/main/java/org/togetherjava/tjbot/features/tophelper/TopHelpersMessageListener.java
Labels: enhancement, priority: normal

#765 removed vc activity command
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/basic/VcActivityCommand.java
Labels: enhancement, priority: normal

#769 Fixed bug with MediaOnlyChannelListener when user closed DMs
  application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java
Labels: bug, priority: normal

#767 MessageUtils#extractCode out of bounds
  application/src/main/java/org/togetherjava/tjbot/features/utils/MessageUtils.java
  application/src/test/java/org/togetherjava/tjbot/features/utils/MessageUtilsTest.java
Labels: bug, priority: normal

#773 Fix website bug with widget on mobile
  website/src/main/resources/public/index.html
Labels: bug, priority: normal

#776 Bugfix ScamBlocker fails on DM
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
Labels: bug, priority: normal

#783 SlashCommandEducator should check length
  application/src/main/java/org/togetherjava/tjbot/features/basic/SlashCommandEducator.java
  application/src/test/java/org/togetherjava/tjbot/features/basic/SlashCommandEducatorTest.java
Labels: enhancement, priority: normal

#786 ScamBlocker crashes if given empty list of actions bug
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
Labels: bug, priority: normal
