Repository Together-Java/TJ-Bot, pull requests merged in 2023-12, with the labels that each got.

#971 upgrade gradle wrapper to 8.5
  application/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: priority: normal

#976 fixed thread transfers
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
Labels: enhancement, priority: normal

#972 upgrade java to 21
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/releases.yaml
  README.md
  application/build.gradle
  build.gradle
Labels: priority: normal

#986 handling error when member left guild
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
Labels: bug, priority: normal
