Repository Together-Java/TJ-Bot, pull requests merged in 2024-01, with the labels that each got.

#975 BugFix: Bot mentions itself in Help-Thread at Timeout
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: bug

#981 Continue/feature/reference gh
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubReference.java
  application/src/main/java/org/togetherjava/tjbot/commands/github/package-info.java
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/FileSharingMessageListener.java
Labels: enhancement, new command, priority: normal

#1012 adds doc for public constructors to fix sonar issues
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubCommand.java
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubReference.java
Labels: documentation, priority: low
