Repository Together-Java/TJ-Bot, pull requests merged in 2024-04, with the labels that each got.

#1078 refactor HelpThreadCreatedListener
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
Labels: bug, priority: major

#1037 Java RSS Feed
  application/build.gradle
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/config/RSSFeed.java
  application/src/main/java/org/togetherjava/tjbot/config/RSSFeedsConfig.java
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/javamail/RSSHandlerRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/javamail/package-info.java
  application/src/main/resources/db/V14__Add_Rss_Feed_Cache.sql
Labels: enhancement, priority: normal

#1098 Proper RSS default config
  application/config.json.template
Labels: enhancement
