Repository Together-Java/TJ-Bot, pull requests merged in 2024-03, with the labels that each got.

#1046 AI response should be in embed
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/AIResponseParser.java
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptService.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/test/java/org/togetherjava/tjbot/features/chatgpt/AIResponseParserTest.java
Labels: priority: major

#1061 Bugfix/GitHub reference
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubReference.java
Labels: bug, priority: critical

#1063 Release v4.9.1
  application/src/main/java/org/togetherjava/tjbot/commands/github/GitHubReference.java
Labels: release

#1040 GitHub Reference feature is in wrong package #1019
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/github/GitHubCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/github/GitHubReference.java
  application/src/main/java/org/togetherjava/tjbot/features/github/package-info.java
Labels: priority: normal

#1062 made tags command ephemeral
  application/src/main/java/org/togetherjava/tjbot/features/tags/TagsCommand.java
  application/src/test/java/org/togetherjava/tjbot/features/tags/TagsCommandTest.java
Labels: enhance command, priority: major

#1068 handle threads when authorId found
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
Labels: bug, priority: major

#1065 fixed dismiss buttons
  application/src/main/java/org/togetherjava/tjbot/features/code/CodeMessageHandler.java
  application/src/main/java/org/togetherjava/tjbot/features/filesharing/FileSharingMessageListener.java
  application/src/main/java/org/togetherjava/tjbot/features/mathcommands/TeXCommand.java
Labels: bug, priority: critical

#1041 Fix: Pre-commit hook includes untracked files in commits
  scripts/pre-commit
Labels: bug, priority: critical

#1076 Removed now obsolete HelperPrune routine (config change)
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/Config.java
  application/src/main/java/org/togetherjava/tjbot/config/HelperPruneConfig.java
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java
Labels: enhancement

#1069 Remove footers
  application/src/main/java/org/togetherjava/tjbot/features/moderation/WhoIsCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/tags/TagManageCommand.java
Labels: enhancement, priority: low
