Repository Together-Java/TJ-Bot, pull requests merged in 2024-02, with the labels that each got.

#1022 Fix encoding issues with intellij
  build.gradle
Labels: bug

#994 Bug/gpt response compact
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptService.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
Labels: enhancement, priority: major

#1016 replace getAsTag() with getName() on user entity
  application/src/main/java/org/togetherjava/tjbot/features/moderation/BanCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/KickCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/ModerationUtils.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/MuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/NoteCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/QuarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/RejoinModerationRoleListener.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/UnbanCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/UnmuteCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/UnquarantineCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/WarnCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/WhoIsCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/audit/AuditCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/audit/ModAuditLogRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/audit/ModAuditLogWriter.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/modmail/ModMailCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/temp/TemporaryModerationRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java
  application/src/test/java/org/togetherjava/tjbot/features/reminder/RemindRoutineTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/JdaTester.java
Labels: priority: low

#1018 ChatGPT Auto-Answer should not be posted when image
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
  application/src/main/java/org/togetherjava/tjbot/features/tags/TagCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/utils/LinkDetection.java
  application/src/main/java/org/togetherjava/tjbot/features/utils/LinkPreviews.java
  application/src/main/java/org/togetherjava/tjbot/features/utils/MessageUtils.java
  build.gradle
Labels: priority: normal
