Repository Together-Java/TJ-Bot, pull requests merged in 2025-07, with the labels that each got.

#1071 Bump Java Version to 24
  .github/workflows/basic-checks.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/releases.yaml
  README.md
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/features/code/CodeMessageHandler.java
  application/src/main/java/org/togetherjava/tjbot/features/componentids/ComponentIdStore.java
  application/src/main/java/org/togetherjava/tjbot/features/github/GitHubReference.java
  application/src/main/java/org/togetherjava/tjbot/features/help/GuildLeaveCloseThreadListener.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java
  application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/ReportCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/attachment/BlacklistedAttachmentListener.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/modmail/ModMailCommand.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/utils/LinkPreviews.java
  application/src/test/java/org/togetherjava/tjbot/features/SlashCommandAdapterTest.java
  application/src/test/java/org/togetherjava/tjbot/jda/ButtonClickEventBuilder.java
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: priority: normal, dependencies

#1272 version bumps, removed some warnings
  application/build.gradle
  application/src/main/java/org/togetherjava/tjbot/features/jshell/renderer/RendererUtils.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetector.java
  application/src/main/java/org/togetherjava/tjbot/features/rss/RSSHandlerRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/tags/TagManageCommand.java
  build.gradle
Labels: enhancement, dependencies

#1273 Merge JUnit dependency versions
  application/build.gradle
  build.gradle
  formatter/build.gradle
Labels: dependencies

#1265 fix: Handle empty message content for suggestion threads
  application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java
Labels: bug, priority: normal

#1279 Block image-based scam messages
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/ScamBlockerConfig.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetector.java
  application/src/test/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetectorTest.java
Labels: enhancement, priority: major, config-changes

#1281 Scam Blocker fine-tuning
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetector.java
  application/src/test/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetectorTest.java
Labels: enhancement, priority: major, config-changes
