Repository Together-Java/TJ-Bot, pull requests merged in 2025-09, with the labels that each got.

#1317 GitHub API increased page size (30 to 1000), reduces load time (30s to 1s)
  application/src/main/java/org/togetherjava/tjbot/features/github/GitHubCommand.java
Labels: enhancement

#1319 Detect attachment scam regardless of case (jpg vs JPG)
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/Attachment.java
  application/src/test/java/org/togetherjava/tjbot/features/moderation/scam/ScamDetectorTest.java
Labels: bug, priority: normal

#1324 Support Video Preview in RSS Feeds
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/config/RSSFeedsConfig.java
  application/src/main/java/org/togetherjava/tjbot/features/rss/RSSHandlerRoutine.java
Labels: enhancement, config-changes

#1325 Fix: audit message being empty for attachment-only scam posts (#1300)
  application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java
Labels: enhancement
