Repository Together-Java/TJ-Bot, pull requests merged in 2025-06, with the labels that each got.

#1208 Optimize auto prune routine
  application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java
Labels: bug, priority: normal

#1125 Feature: Add useful links to ChatGPT response
  application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
Labels: enhancement, priority: normal

#1263 Friendlier handling of default webhook values on bot launch
  application/src/main/java/org/togetherjava/tjbot/logging/discord/DiscordLogging.java
Labels: enhancement

#1264 Switch to new RSS feed
  application/config.json.template
  application/src/main/java/org/togetherjava/tjbot/features/Features.java
  application/src/main/java/org/togetherjava/tjbot/features/rss/RSSHandlerRoutine.java
  application/src/main/java/org/togetherjava/tjbot/features/rss/package-info.java
Labels: enhancement

#1269 Bump to log4j-slf4j2-impl v2.25.0
  application/build.gradle
Labels: dependencies

#1268 Fix RSS Headers
  application/src/main/java/org/togetherjava/tjbot/features/rss/RSSHandlerRoutine.java
Labels: bug
